// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHyrrzmqcQM6UZyxyvix2d6F4BRhKRsA4',
    appId: '1:1000232709789:web:68acb50127a658ea21ee74',
    messagingSenderId: '1000232709789',
    projectId: 'treely-8c2c8',
    authDomain: 'treely-8c2c8.firebaseapp.com',
    storageBucket: 'treely-8c2c8.appspot.com',
    measurementId: 'G-V2XLH32Q6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB16GtVExlUrpMLlcveKdFkb6Pzi_BbGyU',
    appId: '1:1000232709789:android:0c81a5c5e5b01a8521ee74',
    messagingSenderId: '1000232709789',
    projectId: 'treely-8c2c8',
    storageBucket: 'treely-8c2c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCucv85TR8qD7tar50RdNs7T0zCUAkMvDg',
    appId: '1:1000232709789:ios:4bc05ca3b113df4d21ee74',
    messagingSenderId: '1000232709789',
    projectId: 'treely-8c2c8',
    storageBucket: 'treely-8c2c8.appspot.com',
    iosClientId: '1000232709789-hsccncgn9em207jt7tpg77hhiuhbkdv0.apps.googleusercontent.com',
    iosBundleId: 'com.treely.epics.treely',
  );
}
